### ISSUE TITLE
Kan Ban Board Setup: Recipe App

### ISSUE THREAD

**Issue by levy002** [levy002/recipe-app#9]
### Hello @reviewer, we are two on our team:

-   Team 1 => @Debas-31
-  Team 2 = @levy002 

[Project Link](https://github.com/users/levy002/projects/2).

### Thank you for reviewing our project. :handshake:

**Comment by arslanbisharat** [comment]
Hi @levy002 & @Debas-31,
Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights

- Project has met all the technical aspects you needed for this project. Keep rocking! ✔️ 


## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
